---
- name: Install and start Apache HTTP Server
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes


