---
- name: Install and start Apache HTTP Server
  hosts: webservers
  become: yes

  tasks:
    - name: Stop Nginx
      service:
        name: nginx
        state: stopped

    - name: Disable Nginx
      service:
        name: nginx
        enabled: no

    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes

