---
- name: Install and start apache http service
  hosts: webservers
  become: yes

  tasks:

   
    - name: stopping nginx
      service: 
        name: nginx
        state: stopped

    - name: disable Nginx
      service:
        name: nginx
        state: started
        enabled: no

    - name: Ensure apache is installed
      yum:
        name: httpd
        state: present

    - name: Ensure apache is running
      service:
        name: apache
        state: started
        enabled: yes
